### ISSUE TITLE
Очень нужен функционал.

### ISSUE THREAD

**Issue by KostyaRKG** [GyverLibs/Stamp#1]
Есть одна идея, и очень нужен функционал добавления минут, часов, дней, месяцев и лет. Естественно, и уменьшение тоже.
На сколько я понял, в библиотеке уже есть функционал добавления минут, часов и дней.

Было бы круто, если бы вы объяснили, как добавлять или отнимать месяцы и годы?

**Comment by GyverLibs** [comment]
Это невозможно, т.к. и месяц и год состоят из разного количества дней. Если нужно что то "приблизительное", можно прибавить 30 дней (месяц) или 365 дней (год)

**Comment by KostyaRKG** [comment]
Не возможно в вашей библиотеке или вообще? Нет ничего не возможного! Для всего есть свой алгоритм.

**Comment by GyverLibs** [comment]
Предлагаю ещё раз прочитать сообщение)

**Comment by KostyaRKG** [comment]
Меня приблизительно не устраивает. И определить високосный год всегда можно. И можно завести массив макс дней для каждого месяца. И для второго месяца плюсовать один день если это высокосный. что тут нереального?

**Comment by GyverLibs** [comment]
Это бессмыслица)) если нужно прибавить год - достаточно изменить переменную year. То же самое с месяцем

**Comment by KostyaRKG** [comment]
Но если к примерубыл год 2024 02 29 00:00:00 а я меняю год на 23 или 25 то количество дней в месяце должны изменится на 28.

**Comment by GyverLibs** [comment]
"Прибавить месяц" слишком неоднородное понятие из за разного количества дней в месяце, поэтому его нет в библиотеке
- Можно прибавить именно цифру месяца. Но что тогда делать с числом, если в следующем месяце такого числа нет? 
  - округлять до максимального?
  - или переносить на следущий месяц?
- Можно прибавить число дней, соответствующее количеству дней в текущем месяце
- Можно прибавить 30 дней как среднее значение

И то же самое с годом. Это 4 разных варианта реализации, и непонятно кому какой пригодится
